language: python
python:
  - 3.6
before_install:
  - env
  - whoami
  - cat /etc/issue
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r requirements.txt
  - pip install .
  - pip list
script: 
  - flake8 organizer
  - pytest

