language: python
python:
  - 3.6
install:
  - pip install .
  - pip install https://github.com/ashleygould/moto/archive/ashley.zip
  - pip install -r requirements.txt
script: 
  - flake8 organizer
  - pytest

