language: python
python:
  - 3.6
before_install:
  - env
  - whoami
  - cat /etc/issue
install:
  - pip install .
  - pip install https://github.com/ashleygould/moto/archive/ashley.zip
  - pip install -r requirements.txt
script: 
  - flake8 organizer
  - pytest --cov=organizer --cov-report term-missing --no-print-log

