language: python
python:
  - 3.6
before_install:
  - env
  - whoami
  - cat /etc/issue
install:
  - pip install -r requirements.txt
  - pip install https://github.com/spulec/moto/archive/master.zip
  - pip install .
script: 
  - flake8 organizer
  - pytest

